-- MIGRAÇÃO DE CATÁLOGO MDF (PHASE 1) --

-- LIMPEZA INICIAL (Cuidado: apaga dados existentes dessas tabelas)
DROP TABLE IF EXISTS combinacoes_padroes CASCADE;
DROP TABLE IF EXISTS padroes_mdf CASCADE;
DROP TABLE IF EXISTS colecoes_mdf CASCADE;
DROP TABLE IF EXISTS fabricantes_mdf CASCADE;

-- 1. TABELA: fabricantes_mdf
CREATE TABLE fabricantes_mdf (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    logo_url TEXT,
    site_oficial TEXT,
    catalogo_url TEXT,
    total_padroes INTEGER,
    ano_catalogo INTEGER,
    descricao TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABELA: colecoes_mdf
CREATE TABLE colecoes_mdf (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fabricante_id BIGINT REFERENCES fabricantes_mdf(id) ON DELETE CASCADE,
    nome VARCHAR(150) NOT NULL,
    ano_lancamento INTEGER,
    conceito TEXT,
    inspiracao TEXT,
    imagem_destaque_url TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABELA: padroes_mdf
CREATE TABLE padroes_mdf (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fabricante_id BIGINT REFERENCES fabricantes_mdf(id) ON DELETE CASCADE,
    colecao_id BIGINT REFERENCES colecoes_mdf(id) ON DELETE SET NULL,
    
    -- Identificação
    codigo VARCHAR(50),
    nome VARCHAR(150) NOT NULL,
    linha VARCHAR(100),
    
    -- Características Visuais
    categoria VARCHAR(50), -- 'madeirado', 'unicolor', 'metalizado', 'pedra', 'tecido'
    cor_base VARCHAR(50),
    cor_secundaria VARCHAR(50),
    tonalidade VARCHAR(50), -- 'claro', 'medio', 'escuro'
    
    -- Acabamento
    acabamento VARCHAR(100), -- 'Matt Soft', 'SuperMatt', 'Alto Brilho', etc
    textura VARCHAR(100), -- 'Lisa', 'Poro', 'Relevo', 'Deep Wood', etc
    brilho VARCHAR(50), -- 'Fosco', 'Semi-Brilho', 'Alto Brilho'
    
    -- Propriedades Técnicas
    resistencia_umidade BOOLEAN DEFAULT FALSE,
    resistencia_cupim BOOLEAN DEFAULT FALSE,
    resistencia_bacteria BOOLEAN DEFAULT FALSE,
    resistencia_uv BOOLEAN DEFAULT FALSE,
    resistencia_riscos BOOLEAN DEFAULT FALSE,
    
    -- Espessuras Disponíveis
    espessuras_disponiveis INTEGER[], -- [15, 18, 25]
    
    -- Aplicações Recomendadas
    aplicacoes TEXT[], -- ['Cozinha', 'Banheiro', 'Quarto']
    uso_interno BOOLEAN DEFAULT TRUE,
    uso_externo BOOLEAN DEFAULT FALSE,
    
    -- Mídia
    imagem_url TEXT,
    imagem_ambiente_url TEXT,
    textura_sketchup_url TEXT,
    
    -- Descrição
    descricao TEXT,
    inspiracao TEXT,
    combinacoes_sugeridas TEXT[],
    
    -- Status
    lancamento BOOLEAN DEFAULT FALSE,
    ano_lancamento INTEGER,
    disponivel BOOLEAN DEFAULT TRUE,
    
    -- SEO/Busca
    tags TEXT[],
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABELA: combinacoes_padroes
CREATE TABLE combinacoes_padroes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    padrao_principal_id BIGINT REFERENCES padroes_mdf(id) ON DELETE CASCADE,
    padrao_combinado_id BIGINT REFERENCES padroes_mdf(id) ON DELETE CASCADE,
    tipo_combinacao VARCHAR(50), -- 'contraste', 'harmonico', 'monocromatico'
    aplicacao VARCHAR(100), -- 'Cozinha completa', 'Guarda-roupa'
    imagem_exemplo_url TEXT,
    pontuacao INTEGER DEFAULT 5, -- 1-10 (qualidade da combinação)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- HABILITAR RLS e POLÍTICAS DE ACESSO PÚBLICO
ALTER TABLE fabricantes_mdf ENABLE ROW LEVEL SECURITY;
ALTER TABLE colecoes_mdf ENABLE ROW LEVEL SECURITY;
ALTER TABLE padroes_mdf ENABLE ROW LEVEL SECURITY;
ALTER TABLE combinacoes_padroes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Leitura Pública Fabricantes" ON fabricantes_mdf FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Colecoes" ON colecoes_mdf FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Padroes" ON padroes_mdf FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Combinacoes" ON combinacoes_padroes FOR SELECT USING (true);

-- SEED DATA (POPULAR TABELAS)

-- 1. Fabricantes
INSERT INTO fabricantes_mdf (id, nome, site_oficial, total_padroes, ano_catalogo, descricao) VALUES
(1, 'Guararapes', 'https://www.guararapes.com.br', 80, 2025, 'Líder em variedade com tecnologia exclusiva'),
(2, 'Arauco', 'https://arauco.com.br', 80, 2024, 'Referência mundial em sustentabilidade'),
(3, 'Eucatex', 'https://www.eucatex.com.br', 58, 2024, 'Inovação e qualidade em painéis'),
(4, 'Duratex', 'https://www.duratexmadeira.com.br', 70, 2024, 'Tradição e durabilidade'),
(5, 'Placas Brasil', 'https://placasdobrasil.com.br', 50, 2024, 'Padrões com a essência brasileira');

-- Ajustar a sequência do ID após inserts manuais
SELECT setval('fabricantes_mdf_id_seq', (SELECT MAX(id) FROM fabricantes_mdf));

-- 2. Coleções
INSERT INTO colecoes_mdf (id, fabricante_id, nome, ano_lancamento, conceito, inspiracao) VALUES
(1, 1, 'Chroma Collection', 2024, 'Celebração 40 anos com foco em off-whites', 'Antecipação de tendências com foco em off-whites'),
(2, 1, 'Mageo', 2024, 'Madeira + Geometria', 'Marchetaria moderna'),
(3, 2, 'Tons do Brasil', 2024, 'Homenagem à diversidade brasileira', 'Paisagens, culturas e biomas do Brasil'),
(4, 3, 'Origens Nativas', 2024, 'Resgate ancestralidade brasileira', 'Florestas e tradições dos povos brasileiros');

SELECT setval('colecoes_mdf_id_seq', (SELECT MAX(id) FROM colecoes_mdf));

-- 3. Padrões (Exemplos Iniciais)
INSERT INTO padroes_mdf (
  fabricante_id, colecao_id, nome, linha, categoria, 
  cor_base, tonalidade, acabamento, textura, brilho,
  resistencia_umidade, resistencia_cupim, resistencia_bacteria,
  espessuras_disponiveis, aplicacoes, 
  descricao, inspiracao, combinacoes_sugeridas,
  lancamento, ano_lancamento, tags
) VALUES 
-- Guararapes / Lumen
(
  1, 1, 'Lumen', 'Off White Collection', 'unicolor',
  'Off-white amarelado', 'claro', 'MR RUC', 'Lisa', 'Fosco',
  true, true, true,
  ARRAY[15, 18, 25], 
  ARRAY['Cozinha', 'Banheiro', 'Lavanderia'],
  'Tom extremamente delicado amarelado que transmite a vivacidade da luz solar',
  'Luz do sol, acolhimento', ARRAY['Breeze', 'Cloud', 'Carvalho'],
  true, 2024, ARRAY['off-white', 'neutro', 'claro', 'acolhedor', 'moderno']
),
-- Arauco / Cristalina
(
  2, 3, 'Cristalina', 'Tons do Brasil', 'madeirado',
  'Bege claro', 'claro', 'Standard', 'Veios naturais', 'Semi-Brilho',
  false, false, false,
  ARRAY[15, 18], 
  ARRAY['Sala', 'Quarto', 'Escritório'],
  'Inspirado no solo de Goiás e na Chapada dos Veadeiros',
  'Solo de Goiás, Chapada dos Veadeiros', ARRAY['Verde', 'Azul Marinho'],
  false, 2024, ARRAY['brasileiro', 'natural', 'madeira', 'cerrado']
),
-- Eucatex / Louro Freijó
(
  3, 4, 'Louro Freijó', 'BP Poro SuperMatt', 'madeirado',
  'Amarelado natural', 'medio', 'BP Poro SuperMatt', 'Poro profundo', 'Ultra fosco',
  false, false, true,
  ARRAY[15, 18, 25], 
  ARRAY['Móveis alto padrão', 'Painéis', 'Portas'],
  'Exclusivo nas Américas. Variação visual e tátil com extrema naturalidade',
  'Madeiras nobres brasileiras', ARRAY['Preto', 'Cinza'],
  true, 2024, ARRAY['brasileiro', 'nobre', 'exclusivo', 'natural', 'premium']
);

-- FIM DA MIGRAÇÃO
