-- MIGRAÇÃO DE BASE DE CONHECIMENTO TÉCNICO --

-- LIMPEZA INICIAL (Para evitar conflitos de re-execução)
DROP TABLE IF EXISTS materiais_mdf CASCADE;
DROP TABLE IF EXISTS aplicacoes_mdf CASCADE;
DROP TABLE IF EXISTS corredicas CASCADE;
DROP TABLE IF EXISTS especificacoes_instalacao_corredicas CASCADE;
DROP TABLE IF EXISTS sistemas_porta_correr CASCADE;
DROP TABLE IF EXISTS tecnicas_acabamento CASCADE;
DROP TABLE IF EXISTS calculos_tecnicos CASCADE;
DROP TABLE IF EXISTS capacidade_carga_prateleiras CASCADE;
DROP TABLE IF EXISTS tipos_moveis CASCADE;
DROP TABLE IF EXISTS parafusos_pecas CASCADE;

-- 1. Materiais MDF
CREATE TABLE IF NOT EXISTS materiais_mdf (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    espessura_mm NUMERIC NOT NULL UNIQUE, -- Adicionado UNIQUE para permitir Referência (Foreign Key)
    categoria TEXT CHECK (categoria IN ('fino', 'medio', 'grosso')),
    densidade_kg_m3 NUMERIC,
    peso_chapa_kg NUMERIC,
    largura_padrao_mm NUMERIC DEFAULT 1830,
    altura_padrao_mm NUMERIC DEFAULT 2750,
    preco_m2 NUMERIC,
    fabricante TEXT,
    observacoes TEXT
);

-- 2. Aplicações MDF
CREATE TABLE IF NOT EXISTS aplicacoes_mdf (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    espessura_mm NUMERIC REFERENCES materiais_mdf(espessura_mm) ON DELETE SET NULL, -- Relacionamento lógico, idealmente seria por ID mas o dado veio por espessura
    aplicacao TEXT NOT NULL,
    tipo_aplicacao TEXT,
    capacidade_carga_kg NUMERIC,
    vao_maximo_mm NUMERIC,
    prioridade INTEGER
);

-- 3. Corrediças
CREATE TABLE IF NOT EXISTS corredicas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tipo TEXT NOT NULL,
    comprimento_mm NUMERIC NOT NULL,
    capacidade_carga_kg NUMERIC,
    extracao TEXT,
    amortecimento BOOLEAN DEFAULT FALSE,
    preco_par NUMERIC,
    fabricante TEXT,
    modelo TEXT,
    observacoes TEXT
);

-- 4. Especificações de Instalação de Corrediças
CREATE TABLE IF NOT EXISTS especificacoes_instalacao_corredicas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tipo_corredica TEXT NOT NULL,
    espaco_lateral_mm NUMERIC,
    espaco_lateral_maximo_mm NUMERIC,
    espaco_vertical_mm NUMERIC,
    profundidade_borda_mm NUMERIC,
    parafusos_gaveta_min INTEGER,
    parafusos_gaveta_max INTEGER,
    parafusos_movel_min INTEGER,
    parafusos_movel_max INTEGER,
    posicao_gaveta TEXT,
    posicao_movel TEXT,
    observacoes TEXT
);

-- 5. Sistemas de Porta de Correr
CREATE TABLE IF NOT EXISTS sistemas_porta_correr (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tipo TEXT NOT NULL,
    nome TEXT NOT NULL,
    trilho_superior BOOLEAN,
    trilho_inferior BOOLEAN,
    capacidade_carga_kg NUMERIC,
    material_trilho TEXT,
    espessura_porta_min_mm NUMERIC,
    espessura_porta_max_mm NUMERIC,
    profundidade_extra_mm NUMERIC,
    preco_kit NUMERIC,
    observacoes TEXT
);

-- 6. Técnicas de Acabamento
CREATE TABLE IF NOT EXISTS tecnicas_acabamento (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome TEXT NOT NULL,
    descricao TEXT,
    espessura_adicional_mm NUMERIC,
    custo_adicional_percentual NUMERIC,
    tempo_extra_horas NUMERIC,
    complexidade TEXT,
    beneficios TEXT,
    desvantagens TEXT,
    passo_a_passo TEXT
);

-- 7. Cálculos Técnicos
CREATE TABLE IF NOT EXISTS calculos_tecnicos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tipo_calculo TEXT NOT NULL,
    formula TEXT NOT NULL,
    descricao TEXT,
    exemplo TEXT,
    observacoes TEXT
);

-- 8. Capacidade de Carga Prateleiras
CREATE TABLE IF NOT EXISTS capacidade_carga_prateleiras (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    espessura_mm NUMERIC,
    comprimento_mm NUMERIC,
    carga_maxima_kg NUMERIC,
    tipo_fixacao TEXT,
    observacoes TEXT
);

-- 9. Tipos de Móveis
CREATE TABLE IF NOT EXISTS tipos_moveis (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome TEXT NOT NULL,
    categoria TEXT,
    espessura_recomendada_mm NUMERIC,
    usa_tamponamento BOOLEAN,
    usa_gavetas BOOLEAN,
    usa_portas_correr BOOLEAN,
    tipo_porta TEXT,
    altura_padrao_mm NUMERIC,
    profundidade_padrao_mm NUMERIC,
    observacoes TEXT
);

-- 10. Parafusos e Peças
CREATE TABLE IF NOT EXISTS parafusos_pecas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tipo TEXT NOT NULL,
    medida TEXT,
    aplicacao TEXT,
    quantidade_recomendada TEXT,
    preco_caixa_100 NUMERIC,
    preco_par NUMERIC,
    preco_unidade NUMERIC
);

-- Habilitar RLS e permitir Leitura Pública (Reference Data)
ALTER TABLE materiais_mdf ENABLE ROW LEVEL SECURITY;
ALTER TABLE aplicacoes_mdf ENABLE ROW LEVEL SECURITY;
ALTER TABLE corredicas ENABLE ROW LEVEL SECURITY;
ALTER TABLE especificacoes_instalacao_corredicas ENABLE ROW LEVEL SECURITY;
ALTER TABLE sistemas_porta_correr ENABLE ROW LEVEL SECURITY;
ALTER TABLE tecnicas_acabamento ENABLE ROW LEVEL SECURITY;
ALTER TABLE calculos_tecnicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE capacidade_carga_prateleiras ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipos_moveis ENABLE ROW LEVEL SECURITY;
ALTER TABLE parafusos_pecas ENABLE ROW LEVEL SECURITY;

-- Política de Leitura Pública para todas as tabelas
CREATE POLICY "Leitura Pública Materiais" ON materiais_mdf FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Aplicações" ON aplicacoes_mdf FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Corrediças" ON corredicas FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Instalação" ON especificacoes_instalacao_corredicas FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Portas" ON sistemas_porta_correr FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Acabamento" ON tecnicas_acabamento FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Cálculos" ON calculos_tecnicos FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Carga" ON capacidade_carga_prateleiras FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Móveis" ON tipos_moveis FOR SELECT USING (true);
CREATE POLICY "Leitura Pública Peças" ON parafusos_pecas FOR SELECT USING (true);

-- INSERÇÃO DE DADOS (SEED)

INSERT INTO materiais_mdf (id, espessura_mm, categoria, densidade_kg_m3, peso_chapa_kg, largura_padrao_mm, altura_padrao_mm, preco_m2, fabricante, observacoes) VALUES
(1, 3, 'fino', 670, 15.2, 1830, 2750, 45.00, 'Duratex', 'Ideal para fundos de móveis, revestido dupla face obrigatório'),
(2, 6, 'fino', 670, 30.4, 1830, 2750, 52.00, 'Duratex', 'Muito usado para tamponamento e engrossamento'),
(3, 9, 'fino', 670, 45.6, 1830, 2750, 58.00, 'Guararapes', 'Fundos de móveis e estrutura de gavetas pequenas'),
(4, 12, 'medio', 670, 60.8, 1830, 2750, 72.00, 'Duratex', 'Estrutura interna de gavetas, cabeceiras fixas na parede'),
(5, 15, 'medio', 670, 76.0, 1830, 2750, 85.00, 'Duratex', 'Espessura MAIS COMUM - Estrutura/caixaria padrão'),
(6, 18, 'medio', 660, 91.2, 1830, 2750, 95.00, 'Arauco', 'Portas, gavetas, prateleiras médias, instalação de LEDs'),
(7, 20, 'grosso', 650, 101.3, 1830, 2750, 110.00, 'Guararapes', 'Prateleiras com peso médio'),
(8, 25, 'grosso', 650, 126.6, 1830, 2750, 135.00, 'Duratex', 'Tampos, prateleiras pesadas, portas grossas, estrutura robusta'),
(9, 30, 'grosso', 640, 151.9, 1830, 2750, 165.00, 'Arauco', 'Alta resistência, móveis especiais');

INSERT INTO aplicacoes_mdf (id, espessura_mm, aplicacao, tipo_aplicacao, capacidade_carga_kg, vao_maximo_mm, prioridade) VALUES
(1, 3, 'Fundo de móveis (contato com parede)', 'vedacao', null, null, 1),
(2, 3, 'Fundo de gavetas pequenas', 'vedacao', null, null, 2),
(3, 6, 'Tamponamento (segunda pele do móvel)', 'acabamento', null, null, 1),
(4, 6, 'Engrossamento de chapas', 'especial', null, null, 2),
(5, 6, 'Portas de correr com perfil alumínio', 'estrutural', null, null, 3),
(6, 9, 'Estrutura de gavetas menores', 'estrutural', null, null, 1),
(7, 12, 'Estrutura interna de gavetas', 'estrutural', null, null, 1),
(8, 12, 'Cabeceiras fixadas na parede', 'estrutural', null, null, 2),
(9, 15, 'Estrutura/caixaria de armários', 'estrutural', null, 300, 1),
(10, 15, 'Laterais de cômodas', 'estrutural', null, null, 1),
(11, 15, 'Painéis de TV e cabeceiras', 'acabamento', null, null, 2),
(12, 15, 'Portas com espelho ou vidro', 'estrutural', null, null, 2),
(13, 18, 'Frentes de portas e gavetas', 'estrutural', null, null, 1),
(14, 18, 'Prateleiras médias', 'estrutural', 25, 360, 1),
(15, 18, 'Tamponamento de módulos', 'acabamento', null, null, 2),
(16, 18, 'Instalação de spots LED (sulcos 8-10mm)', 'especial', null, null, 3),
(17, 25, 'Prateleiras de guarda-roupas (peso)', 'estrutural', 50, 500, 1),
(18, 25, 'Tampos de mesas e bancadas', 'estrutural', 60, null, 1),
(19, 25, 'Portas pesadas', 'estrutural', null, null, 2),
(20, 25, 'Laterais e colunas de geladeiras', 'estrutural', null, null, 2);

INSERT INTO corredicas (id, tipo, comprimento_mm, capacidade_carga_kg, extracao, amortecimento, preco_par, fabricante, modelo, observacoes) VALUES
(1, 'simples', 350, 15, 'parcial', false, 25.00, 'Genérico', 'Simples 350', 'Abertura parcial, mais econômica'),
(2, 'simples', 400, 15, 'parcial', false, 28.00, 'Genérico', 'Simples 400', 'Abertura parcial'),
(3, 'simples', 450, 15, 'parcial', false, 32.00, 'Genérico', 'Simples 450', 'Mais comum em gavetas pequenas'),
(4, 'telescopica', 350, 45, 'total', false, 55.00, 'Soprano', 'Telescópica 350', 'Extração total, silenciosa'),
(5, 'telescopica', 400, 45, 'total', false, 62.00, 'Soprano', 'Telescópica 400', 'Extração total, silenciosa'),
(6, 'telescopica', 450, 45, 'total', false, 68.00, 'Soprano', 'Telescópica 450', 'MAIS COMUM - Extração total'),
(7, 'telescopica', 500, 45, 'total', false, 75.00, 'Soprano', 'Telescópica 500', 'Para gavetas grandes'),
(8, 'telescopica', 450, 45, 'total', true, 95.00, 'Soprano', 'Telescópica 450 Soft', 'Com amortecedor - fechamento suave'),
(9, 'oculta', 450, 45, 'total', true, 125.00, 'Soprano', 'Oculta 450', 'Instalada por baixo, invisível, requer instalador');

INSERT INTO especificacoes_instalacao_corredicas (id, tipo_corredica, espaco_lateral_mm, espaco_lateral_maximo_mm, espaco_vertical_mm, profundidade_borda_mm, parafusos_gaveta_min, parafusos_gaveta_max, parafusos_movel_min, parafusos_movel_max, posicao_gaveta, posicao_movel, observacoes) VALUES
(1, 'telescopica', 12.5, 13, 10, 2, 3, 5, 3, 5, 'Meio da altura lateral', 'Meio da altura lateral + 10mm', 'Puxar extensão para aparecer furos. Começar por furos ovais para ajuste.'),
(2, 'simples', 12.5, 13, 10, 2, 4, 4, 4, 6, 'Base da gaveta', 'Alinhado com posição da gaveta', 'Mínimo 2 parafusos frente, 1 centro, 1 trás de cada lado no móvel'),
(3, 'oculta', 0, 2, 10, 0, 4, 6, 4, 6, 'Embaixo da gaveta (centro)', 'Base interna do móvel', 'Instalação complexa - requer profissional. Ajuste preciso essencial.');

INSERT INTO sistemas_porta_correr (id, tipo, nome, trilho_superior, trilho_inferior, capacidade_carga_kg, material_trilho, espessura_porta_min_mm, espessura_porta_max_mm, profundidade_extra_mm, preco_kit, observacoes) VALUES
(1, 'embutido', 'Sistema Embutido/Coplanar', true, true, 50, 'aluminio', 15, 25, 50, 180.00, 'Trilhos embutidos no móvel. Visual discreto e elegante. Ideal para móveis planejados.'),
(2, 'sobreposto', 'Sistema Sobreposto/Suspenso', true, false, 80, 'aluminio', 18, 25, 50, 220.00, 'SEM trilho inferior - não junta sujeira. Ideal para portas grandes. Porta suspensa.'),
(3, 'apoiado', 'Sistema Apoiado (Base)', false, true, 60, 'aluminio', 18, 30, 50, 150.00, 'Porta desliza sobre trilho no chão/base. Ideal para portas pesadas.'),
(4, 'coplanar', 'Sistema Coplanar Premium', true, false, 70, 'aluminio', 15, 25, 50, 280.00, 'Portas alinhadas quando fechadas. Design moderno. Estantes e painéis TV.'),
(5, 'expostos', 'Sistema Trilhos Expostos (Industrial)', true, false, 100, 'aco', 20, 40, 100, 450.00, 'Trilhos visíveis estilo industrial. Portas grandes e pesadas. Visual diferenciado.');

INSERT INTO tecnicas_acabamento (id, nome, descricao, espessura_adicional_mm, custo_adicional_percentual, tempo_extra_horas, complexidade, beneficios, desvantagens, passo_a_passo) VALUES
(1, 'Tamponamento', 'Camada extra de MDF (geralmente 6mm) que reveste toda a caixaria do móvel, criando uma ''segunda pele''', 6, 25.00, 2.5, 'media', 'Esconde parafusos sem tapa-furos, maior resistência estrutural, acabamento sofisticado, permite cores diferentes (miolo branco + externo amadeirado), aparência robusta', 'Custo 25% maior, peso adicional, profundidade extra necessária', '1) Caixa pronta; 2) Cortar MDF fundo + 2 laterais + ripa superior; 3) Colar laterais no fundo; 4) Encaixar caixa; 5) Parafusar interno>externo; 6) Colar ripa superior; 7) Instalar dobradiças'),
(2, 'Engrossamento', 'Combinação de duas ou mais chapas de MDF para atingir espessuras não disponíveis no mercado', 0, 15.00, 1.0, 'baixa', 'Permite espessuras customizadas (ex: 12mm + 3mm = 15mm), cores diferentes nas faces (ex: externa amadeirada + interna branca), flexibilidade de projeto', 'Custo um pouco maior, necessita cola de qualidade, requer prensa ou grampos', '1) Cortar peças nas medidas; 2) Aplicar cola uniforme; 3) Prensar por 24h; 4) Finalizar bordas'),
(3, 'Fita de Borda', 'Aplicação de fita (PVC, ABS ou melamínica) nas bordas do MDF para acabamento', 0, 5.00, 0.5, 'baixa', 'Proteção das bordas, acabamento profissional, variedade de cores, resistência à umidade', 'Pode descolar com umidade excessiva, requer cola apropriada', '1) Cortar fita no tamanho; 2) Aplicar cola hotmelt; 3) Pressionar com ferro ou coladeira; 4) Refilar excesso');

INSERT INTO calculos_tecnicos (id, tipo_calculo, formula, descricao, exemplo, observacoes) VALUES
(1, 'Vão livre máximo (prateleiras)', 'vao_maximo_mm = espessura_mm * 20', 'Relação ideal entre espessura do MDF e distância máxima entre apoios para prateleiras sem empenamento', 'MDF 18mm: vao_maximo = 18 * 20 = 360mm (36cm)', 'Para cargas concentradas (não distribuídas), reduzir resultado em 30-40%. Usar suportes invisíveis a cada 400mm para reforço.'),
(2, 'Profundidade armário porta correr', 'profundidade_total = profundidade_util + (numero_portas * 50mm)', 'Cálculo da profundidade necessária para armário com portas de correr, considerando espaço para trilhos', 'Armário 500mm com 2 portas: 500 + (2 * 50) = 600mm de profundidade total', 'Cada porta correndo precisa de aproximadamente 50mm. Para 3 portas = +150mm.'),
(3, 'Quantidade de parafusos (corrediças)', 'parafusos_simples = 16 por gaveta; parafusos_telescopica = 12 a 20 por gaveta', 'Quantidade de parafusos 3,5mm x 14mm necessários para instalação de corrediças', 'Gaveta com corrediça telescópica: mínimo 12 (3 gaveta esq + 3 gaveta dir + 3 móvel esq + 3 móvel dir)', 'Usar parafusos extras para reforço em gavetas pesadas (até 20 total).'),
(4, 'Área de chapa MDF', 'area_m2 = (largura_mm * altura_mm) / 1000000', 'Cálculo de área em m² de uma chapa de MDF padrão', 'Chapa 1830mm x 2750mm: (1830 * 2750) / 1000000 = 5,03 m²', 'Sempre considerar 10-15% de perda no corte para otimização.'),
(5, 'Peso total da chapa', 'peso_kg = area_m2 * espessura_mm * densidade_kg_m3 / 1000', 'Cálculo do peso aproximado de uma chapa de MDF', 'MDF 15mm, densidade 670kg/m³: 5,03 * 15 * 670 / 1000 = 50,5kg', 'Importante para planejamento de transporte e instalação em paredes.');

INSERT INTO capacidade_carga_prateleiras (id, espessura_mm, comprimento_mm, carga_maxima_kg, tipo_fixacao, observacoes) VALUES
(1, 15, 400, 30, 'Apoio lateral', 'Carga distribuída uniformemente'),
(2, 15, 600, 20, 'Apoio lateral', 'Carga distribuída uniformemente'),
(3, 15, 800, 12, 'Apoio lateral + suporte central', 'Recomenda-se suporte invisível no centro'),
(4, 15, 1000, 8, 'Apoio lateral + 2 suportes', 'Necessário suporte a cada 400mm'),
(5, 18, 400, 35, 'Apoio lateral', 'Carga distribuída uniformemente'),
(6, 18, 600, 25, 'Apoio lateral', 'Carga distribuída uniformemente'),
(7, 18, 800, 18, 'Apoio lateral + suporte central', 'Recomenda-se suporte invisível no centro'),
(8, 25, 600, 40, 'Apoio lateral', 'Ideal para guarda-roupas'),
(9, 25, 800, 30, 'Apoio lateral + suporte central', 'Para livros ou objetos pesados'),
(10, 25, 1000, 22, 'Apoio lateral + 2 suportes', 'Suporte a cada 400mm obrigatório');

INSERT INTO tipos_moveis (id, nome, categoria, espessura_recomendada_mm, usa_tamponamento, usa_gavetas, usa_portas_correr, tipo_porta, altura_padrao_mm, profundidade_padrao_mm, observacoes) VALUES
(1, 'Armário de cozinha aéreo', 'cozinha', 15, true, false, false, 'abrir', 700, 300, 'Fixação na parede requer buchas de 8mm. Usar tamponamento para acabamento superior.'),
(2, 'Balcão de cozinha', 'cozinha', 18, true, true, false, 'abrir', 850, 600, 'Tampo 25mm. Mínimo 3 gavetas com corrediças telescópicas.'),
(3, 'Guarda-roupa', 'quarto', 15, true, true, true, 'correr', 2200, 550, 'Prateleiras em 25mm. Portas de correr +50mm por porta na profundidade.'),
(4, 'Rack de TV', 'sala', 18, true, false, false, 'abrir', 600, 400, 'Painel de fundo 15mm. Suporte para TV deve ser fixado em estrutura reforçada.'),
(5, 'Escrivaninha', 'escritorio', 25, false, true, false, null, 750, 600, 'Tampo 25mm obrigatório. Gavetas com corrediças telescópicas.'),
(6, 'Estante/Livreiro', 'sala', 25, false, false, false, null, 1800, 300, 'Prateleiras 25mm para livros. Suportes invisíveis a cada 400mm.'),
(7, 'Gabinete de banheiro', 'banheiro', 18, true, true, false, 'abrir', 600, 450, 'MDF Ultra (resistente à umidade) obrigatório. Vedação de silicone essencial.'),
(8, 'Closet', 'quarto', 15, true, true, true, 'correr', 2400, 600, 'Sistema completo: prateleiras 25mm, gavetas com corrediças ocultas, portas sistema coplanar.');

INSERT INTO parafusos_pecas (id, tipo, medida, aplicacao, quantidade_recomendada, preco_caixa_100, preco_par, preco_unidade) VALUES
(1, 'Parafuso cabeça chata', '3,5mm x 14mm', 'Fixação de corrediças', '100 unidades/móvel médio', 12.00, null, null),
(2, 'Parafuso cabeça chata', '3,5mm x 20mm', 'Montagem de estrutura MDF 15mm', '150 unidades/móvel médio', 15.00, null, null),
(3, 'Parafuso cabeça chata', '4,0mm x 30mm', 'Montagem de estrutura MDF 18-25mm', '100 unidades/móvel grande', 22.00, null, null),
(4, 'Minifix (cavilha + excêntrico)', '15mm', 'Montagem invisível de estruturas', '40 pares/móvel médio', null, 1.50, null),
(5, 'Dobradiça caneco 35mm', '35mm', 'Portas de armário', '2-3 por porta', null, null, 8.50);

-- FIM DA MIGRAÇÃO
